name: Build Release APK


on:
  workflow_dispatch:

  push:
    branches:
      - main


permissions:
  contents: write


jobs:

  build:

    runs-on: ubuntu-latest


    steps:

      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      # 配置 JDK
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17


      # 设置 Gradle 权限
      - name: Grant execute permission
        run: chmod +x ./gradlew


      # 构建签名 APK
      - name: Build Release APK
        run: |
          ./gradlew assembleRelease


      # 生成版本号 YYMMDD-ci编号
      - name: Generate Version
        id: version
        run: |
          DATE=$(date +"%y%m%d")

          COUNT=$(git tag -l "${DATE}-ci*" | wc -l)

          COUNT=$((COUNT+1))

          VERSION="${DATE}-ci${COUNT}"

          echo "version=$VERSION" >> $GITHUB_OUTPUT


      # 创建 Git Tag
      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git tag ${{ steps.version.outputs.version }}

          git push origin ${{ steps.version.outputs.version }}


      # 发布 GitHub Release
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}

          name: ${{ steps.version.outputs.version }}

          body: |
            Automated CI Build

            Version:
            ${{ steps.version.outputs.version }}

            Commit:
            ${{ github.sha }}

          files: |
            app/build/outputs/apk/release/*.apk